### ISSUE TITLE
Fehlerhafte Übersetzung ftw.mail.mail in der Activity Stream 

### ISSUE THREAD

**Issue by mtokmak** [4teamwork/ftw.mail#29]
In der letzten Version des Teamraums (4.3.0 / Falcon) erscheint eine fehlerhafte Übersetzung. Siehe Screenshot:
![89be802e-ce45-11e4-96a9-6913352ea2e4](https://cloud.githubusercontent.com/assets/7469/14918661/696147e6-0e25-11e6-9cad-053ea125be24.png)

**Comment by mbaechtold** [comment]
@jone, this has been resolved in the pull request https://github.com/4teamwork/ftw.mail/pull/38 (see release 2.4.0).
